---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: asterr.mac-rosetta
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles','pyenv']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: asterr.macbook.pulse
      tags: ['pulse', 'work']
    - role: asterr.macbook.vipaccess
      tags: ['vipaccess', 'work']
    - role: asterr.macbook.msoffice
      tags: ['msoffice', 'work']
    - role: asterr.macbook.iterm2
      tags: ['iterm2', 'work']
    - role: gantsign.antigen
      tags: ['oh-my-zsh','work','personal']
      users:
        - username: asterr
          antigen_libraries:
            - name: oh-my-zsh
              env:
                DISABLE_AUTO_UPDATE: '"true"'
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: gcloud
            - name: kubectl
            - name: pyenv
    - role: asterr.macbook.gcloud
      tags: ['gcloud', 'work']
    - role: asterr.macbook.pyenv
      tags: ['pyenv', 'work']
    - role: asterr.macbook.iodata
      tags: ['iodata', 'home']
    - role: asterr.macbook.youtubemusic
      tags: ['youtubemusic', 'home', 'work']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
