---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: asterr.mac-rosetta
    src: git+https://github.com/asterr/ansible-role-mac-rosetta.git

collections:
  - name: geerlingguy.mac
  - name: https://github.com/asterr/ansible-collection-macbook.git
    type: git
