---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: asterr.mac-rosetta
    src: git+https://github.com/asterr/ansible-role-mac-rosetta.git
  - name: gantsign.antigen
  - name: staticdev.pyenv
    src: git+https://github.com/asterr/ansible-role-pyenv.git

collections:
  - name: geerlingguy.mac
  # - name: /Users/asterr/tmp/mac-dev-playbook/modules/ansible-collection-macbook
  #   type: dir
  - name: https://github.com/asterr/ansible-collection-macbook.git
    type: git
  - name: https://github.com/asterr/google.cloud.git
    type: git
